import type { PremiumCar } from '../@types/car';

// Base demonstrativa para MVP. Validar especificações em fonte oficial antes de qualquer uso corporativo real.
export const competitorCars: PremiumCar[] = [
  {
    id: 'toyota-hilux-srx-2024',
    brand: 'Toyota',
    model: 'Hilux SRX',
    year: 2024,
    powerHp: 204,
    torqueNm: 500,
    zeroToHundred: 10.1,
    drivetrain: 'AWD',
    engine: '2.8 Turbodiesel',
    category: 'Picape média',
    highlight: 'Referência tradicional em robustez e revenda no segmento de picapes médias.',
  },
  {
    id: 'chevrolet-s10-high-country-2024',
    brand: 'Chevrolet',
    model: 'S10 High Country',
    year: 2024,
    powerHp: 200,
    torqueNm: 500,
    zeroToHundred: 10.3,
    drivetrain: 'AWD',
    engine: '2.8 Turbodiesel',
    category: 'Picape média',
    highlight: 'Concorrente direta com foco em força, pacote de conforto e uso misto.',
  },
  {
    id: 'mitsubishi-l200-triton-sport-hpe-s-2024',
    brand: 'Mitsubishi',
    model: 'L200 Triton Sport HPE-S',
    year: 2024,
    powerHp: 190,
    torqueNm: 430,
    zeroToHundred: 11.2,
    drivetrain: 'AWD',
    engine: '2.4 Turbodiesel',
    category: 'Picape média',
    highlight: 'Forte apelo fora de estrada e reputação de durabilidade em uso severo.',
  },
  {
    id: 'nissan-frontier-platinum-2024',
    brand: 'Nissan',
    model: 'Frontier Platinum',
    year: 2024,
    powerHp: 190,
    torqueNm: 450,
    zeroToHundred: 11.0,
    drivetrain: 'AWD',
    engine: '2.3 Biturbo Diesel',
    category: 'Picape média',
    highlight: 'Combina cabine confortável, suspensão multilink e proposta de uso familiar/trabalho.',
  },
  {
    id: 'volkswagen-amarok-v6-highline-2024',
    brand: 'Volkswagen',
    model: 'Amarok V6 Highline',
    year: 2024,
    powerHp: 258,
    torqueNm: 580,
    zeroToHundred: 8.0,
    drivetrain: 'AWD',
    engine: '3.0 V6 Turbodiesel',
    category: 'Picape média premium',
    highlight: 'Entrega alto desempenho em potência e torque, com posicionamento mais aspiracional.',
  },
  {
    id: 'jeep-commander-overland-td380-2024',
    brand: 'Jeep',
    model: 'Commander Overland TD380',
    year: 2024,
    powerHp: 170,
    torqueNm: 380,
    zeroToHundred: 11.6,
    drivetrain: 'AWD',
    engine: '2.0 Turbodiesel',
    category: 'SUV 7 lugares',
    highlight: 'SUV familiar com foco em espaço, tração e percepção premium.',
  },
  {
    id: 'toyota-corolla-cross-hybrid-2024',
    brand: 'Toyota',
    model: 'Corolla Cross Hybrid',
    year: 2024,
    powerHp: 122,
    torqueNm: 163,
    zeroToHundred: 13.0,
    drivetrain: 'FWD',
    engine: '1.8 Hybrid Flex',
    category: 'SUV médio híbrido',
    highlight: 'Concorrente forte em eficiência, confiabilidade percebida e proposta híbrida.',
  },
  {
    id: 'hyundai-creta-ultimate-2024',
    brand: 'Hyundai',
    model: 'Creta Ultimate',
    year: 2024,
    powerHp: 120,
    torqueNm: 172,
    zeroToHundred: 11.5,
    drivetrain: 'FWD',
    engine: '1.0 Turbo Flex',
    category: 'SUV compacto',
    highlight: 'Modelo de alto volume com pacote tecnológico e forte presença urbana.',
  },
];
